# Generated by Django 4.2.9 on 2024-01-15 01:03

import ckeditor_uploader.fields
import collabo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("author", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=30)),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        verbose_name="CONTENT"
                    ),
                ),
                (
                    "main_img",
                    models.ImageField(upload_to=collabo.models.image_upload_path),
                ),
                ("bgmusic", models.CharField(max_length=50)),
                ("pay", models.BooleanField(default=True)),
                ("pub_data", models.DateTimeField()),
            ],
        ),
    ]
