# Generated by Django 4.2.9 on 2024-01-15 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collabo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article", old_name="pub_data", new_name="pub_date",
        ),
    ]
