# Generated by Django 4.2.9 on 2024-01-15 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("collabo", "0002_rename_pub_data_article_pub_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="img_artist",
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="article",
            name="music_artist",
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
