# Generated by Django 4.2.9 on 2024-01-15 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("collabo", "0003_article_img_artist_article_music_artist"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="desc",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
